using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SQLite;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace WindowsFormsApplication1
{
    public partial class AddClient_frm : Form
    {
        private SQLiteConnection sql_con;
        public AddClient_frm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            sql_con = new SQLiteConnection
               ("Data Source=inventory.sqlite;Version=3");
        }

        private void AddClient_frm_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'inventoryDataSetOfficiel.Client' table. You can move, or remove it, as needed.
            this.clientTableAdapter1.Fill(this.inventoryDataSetOfficiel.Client);
            clientBindingSource5.AddNew();
            // TODO: This line of code loads data into the 'inventoryDataSet1.Client' table. You can move, or remove it, as needed.
            // TODO: This line of code loads data into the 'abcdDataSet.Client' table. You can move, or remove it, as needed.
            // TODO: This line of code loads data into the 'inventoryDataSet5.Client' table. You can move, or remove it, as needed.
            // TODO: This line of code loads data into the 'inventoryDataSet1.Client' table. You can move, or remove it, as needed.
            // TODO: This line of code loads data into the 'inventoryDataSet.Client' table. You can move, or remove it, as needed.


            Random rand = new Random();
            int a = rand.Next(5);
            string b = "man";

            
                if (a == 0) photoPictureEdit.EditValue = ImageToByte(Properties.Resources.man0);
                if (a == 1) photoPictureEdit.EditValue = ImageToByte(Properties.Resources.man1);
                if (a == 2) photoPictureEdit.EditValue = ImageToByte(Properties.Resources.man2);
                if (a == 3) photoPictureEdit.EditValue = ImageToByte(Properties.Resources.man3);
                if (a == 4) photoPictureEdit.EditValue = ImageToByte(Properties.Resources.man4);

            }

        public static byte[] ImageToByte(Image img)
        {
            ImageConverter converter = new ImageConverter();
            return (byte[])converter.ConvertTo(img, typeof(byte[]));
        }

        public void add_client(string cmd)
        {
            sql_con.Open();
            SQLiteCommand sql_cmd = new SQLiteCommand(cmd, sql_con);
           
         //   byte[] file = (byte[]) photoPictureEdit.EditValue;
           

           
            sql_cmd.Parameters.AddWithValue("nom", nomTextEdit.Text);
            sql_cmd.Parameters.AddWithValue("prénom" , prénomTextEdit.Text);
            sql_cmd.Parameters.AddWithValue("adresse" ,adressTextEdit.Text);
            sql_cmd.Parameters.AddWithValue("datei" ,date_inscriptionDateEdit.Text);
            sql_cmd.Parameters.AddWithValue("daten",date_naissanceDateEdit.Text);
            sql_cmd.Parameters.AddWithValue("paiement",paiementTextEdit.Text);
            sql_cmd.Parameters.AddWithValue("cours" ,0);
            sql_cmd.Parameters.AddWithValue("exam",0);
            sql_cmd.Parameters.AddWithValue("p1",papier1TextEdit.Text);
            
           // SQLiteParameter param = new SQLiteParameter("@photo", System.Data.DbType.Binary);
          //  param.Value = file;
          //  sql_cmd.Parameters.Add(param);
            sql_cmd.Parameters.AddWithValue("photo", photoPictureEdit.EditValue);


            sql_cmd.ExecuteNonQuery();
            sql_con.Close();
        }

        public void showimage()
        {
            sql_con.Open();
            SQLiteCommand sql_cmd = new SQLiteCommand("select photo FROM Client WHERE ID_client=71", sql_con);
           

 
            sql_con.Close();
            
        }

        private void bunifuThinButton21_Click(object sender, EventArgs e)
        {
            

        }

        private void photoTextEdit_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void bunifuThinButton22_Click(object sender, EventArgs e)
        {
            
        }

        private void nomTextEdit_Validating(object sender, CancelEventArgs e)
        {

        }

        private void textEdit1_EditValueChanged(object sender, EventArgs e)
        {

            Random rand = new Random();
            int a = rand.Next(5);
            string b = "man";

            if (textEdit1.Text == "Male")
            { 
                if (a == 0) photoPictureEdit.EditValue = ImageToByte(Properties.Resources.man0);
                if (a == 1) photoPictureEdit.EditValue = ImageToByte(Properties.Resources.man1);
                if (a == 2) photoPictureEdit.EditValue = ImageToByte(Properties.Resources.man2);
                if (a == 3) photoPictureEdit.EditValue = ImageToByte(Properties.Resources.man3);
                if (a == 4) photoPictureEdit.EditValue = ImageToByte(Properties.Resources.man4);
                
            }
            else
            {
                if (a == 0) photoPictureEdit.EditValue = ImageToByte(Properties.Resources.woman0);
                if (a == 1) photoPictureEdit.EditValue = ImageToByte(Properties.Resources.woman1);
                if (a == 2) photoPictureEdit.EditValue = ImageToByte(Properties.Resources.woman2);
                if (a == 3) photoPictureEdit.EditValue = ImageToByte(Properties.Resources.woman3);
                if (a == 4) photoPictureEdit.EditValue = ImageToByte(Properties.Resources.woman4);

            }
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            bool isValid = dxValidationProvider1.Validate();


            string cmd = "INSERT INTO Client (nom, prénom, adress, date_inscription, date_naissance, paiement, id_cours, Id_examen, papier1, papier2, papier3, photo) VALUES (@nom, @prénom, @adresse, @datei, @daten, @paiement, @cours, @exam, @p1, 'o', 'o', @photo)";
            /*            string cmd = "INSERT INTO Client (nom, prénom, adress, date_inscription, date_naissance, paiement, id_cours, Id_examen, papier1, papier2, papier3, photo) VALUES ('52','1','2','3','5','6','7','8','9','10','11','12')";
*/

            if (isValid)
            {
                add_client(cmd);
             //   ucmodule3.instance.clientTableAdapter.Fill(ucmodule3.instance.inventoryDataSet12.Client);
                Close();
            }
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            Close();
        }
    }
}
